# -*- coding: utf-8 -*-
"""GSK_A

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vJ0hhzyLd-q6YqtdORPurVV3EvYR18bo

#1. Import the files

#2. Import libraries
"""

import pandas as pd
import matplotlib.pyplot as plt

"""#3. Read the files"""

clinical = pd.read_excel("clinical-study.xlsx")
protein = pd.read_excel("protein-levels.xlsx")

"""#4. Check the data"""

clinical.head()

protein.head()

clinical.info()

"""#5. Remove duplicates"""

clinical = clinical.drop_duplicates()

"""#6. Remove under-18s"""

clinical = clinical[clinical["age"] >= 18]

"""#7. Remove missing values"""

clinical = clinical.dropna()
protein = protein.dropna()

"""#8. Add BMI"""

clinical["BMI"] = clinical["weight"] / (clinical["height"] ** 2)

"""#9. Merge protein data"""

clinical = clinical.merge(
    protein,
    left_on="subject_id",
    right_on="participant_id",
    how="left"
)

"""#10. Add response label"""

clinical["response_label"] = clinical["RESPONSE"].map({
    "Y": "Responder",
    "N": "Non-Responder"
})

"""#11. Drug vs control response table"""

response_table = pd.crosstab(
    clinical["trt_grp"],
    clinical["response_label"],
    margins=True
)

response_table

"""#12. Response rates"""

response_rate = pd.crosstab(
    clinical["trt_grp"],
    clinical["response_label"],
    normalize="index"
) * 100

response_rate

"""#13. Protein concentration analysis"""

protein_summary = clinical.groupby("response_label")["protein_concentration"].mean()
protein_summary

"""#14. Age analysis"""

age_summary = clinical.groupby("response_label")["age"].mean()
age_summary

"""#15. BMI analysis"""

bmi_summary = clinical.groupby("response_label")["BMI"].mean()
bmi_summary

"""#16.1.Treatment Response Chart"""

response_table_no_total = response_table.drop("All")

response_table_no_total[["Non-Responder", "Responder"]].plot(kind="bar",color=["#808080", "#F57C00"])

plt.title("Response by Treatment Group")
plt.xlabel("Treatment Group")
plt.ylabel("Number of Patients")
plt.xticks(rotation=0)
plt.show()

"""#16.2 Protein Concentration Chart"""

clinical.groupby("response_label")["protein_concentration"].mean().plot(
    kind="bar",
    color=["#808080", "#F57C00"]
)

plt.title("Average Protein Concentration by Response")
plt.xlabel("Response")
plt.ylabel("Average Protein Concentration")
plt.xticks(rotation=0)
plt.show()

"""#16.3 Age Chart"""

clinical.groupby("response_label")["age"].mean().plot(
    kind="bar",
    color=["#808080", "#F57C00"]
)

plt.title("Average Age of Responders vs Non-Responders")
plt.xlabel("Response")
plt.ylabel("Average Age")
plt.xticks(rotation=0)
plt.show()

"""#16.4 BMI Chart"""

clinical.groupby("response_label")["BMI"].mean().plot(
    kind="bar",
    color=["#808080", "#F57C00"]
)

plt.title("Average BMI of Responders vs Non-Responders")
plt.xlabel("Response")
plt.ylabel("Average BMI")
plt.xticks(rotation=0)
plt.show()

response_table = pd.crosstab(
    clinical["trt_grp"],
    clinical["response_label"]
)

response_table["Total"] = response_table.sum(axis=1)

response_table.loc["Total"] = response_table.sum()

response_table.style.background_gradient(cmap="Oranges")
response_table